[package]
name = "my_os"
version = "0.1.0"
authors = ["Riku Inoue <riku.inoue@shiroyagi.co.jp>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
multiboot2 = "0.1.0"